server:
  port: 8012

spring:
  application:
    name: cloud-provider-payment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.200:3306/school?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    druid:
      filters: stat,wall
      aop-patterns: com.rain.admin.*
      stat-view-servlet:
        enabled: true
      web-stat-filter:
        enabled: true
      filter:
        wall:
          config:
            delete-allow: false
        stat:
          merge-sql: false

eureka:
  client:
    #true表示向注册中心注册自己，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8012
    prefer-ip-address: true

mybatis-plus:
  mapper-locations: classpath:mapper\*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0